# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: xcodebuild clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE=

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test